name: Автоматическая сборка раз в три дня

on:
  schedule:
    # Запуск в 00:00 (полночь) каждые 3 дня
    - cron: '0 0 */3 * *'
  # Позволяет запускать сборку вручную кнопкой в любое время
  workflow_dispatch:

jobs:
  build:
    name: Сборка проекта
    runs-on: windows-latest

    steps:
      - name: Копирование кода из репозитория
        uses: actions/checkout@v4

      - name: Установка Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Запуск скрипта сборки (build.py)
        # Ваш скрипт сам ставит библиотеки и собирает EXE
        run: python build.py

      - name: Сохранение готового файла (Артефакт)
        uses: actions/upload-artifact@v4
        with:
          name: Готовый-бинарник-ru-python
          path: |
            dist/
            *.exe
