name: Тест на проверку работоспособности 

on:
  push:
    paths: ['main.py', '.github/workflows/deploy.yml']


  workflow_dispatch: # Возможность ручного запуска

jobs:
  run-code:
    name: Выполнение кода
    runs-on: windows-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка среды Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Установка зависимостей
        run: |
          if (Test-Path requirements.txt) {
              pip install -r requirements.txt
          }

      - name: Запуск скрипта main.py
        env:
          PYTHONUTF8: "1"  
        run: echo "suscersal" | python main.py


